/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_consultoriomedico;

import com.mycompany.projeto_consultoriomedico.Manager.AuthManager;
import com.mycompany.projeto_consultoriomedico.Manager.TokenManager;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TELA_LOGIN_ADM extends javax.swing.JFrame {

    /**
     * Creates new form TELA_LOGIN_ADM
     */
    public TELA_LOGIN_ADM() {
        initComponents();
        setLocationRelativeTo(null);
        TelaUtil.padronizarTela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_LoginADM_Esquerda = new javax.swing.JPanel();
        JLBsenha = new javax.swing.JLabel();
        JLBusuario = new javax.swing.JLabel();
        JTFsenha = new javax.swing.JTextField();
        JTFusuario = new javax.swing.JTextField();
        JLBusuario1 = new javax.swing.JLabel();
        JBTentrar = new javax.swing.JButton();
        JLBalterarLogin = new javax.swing.JLabel();
        Panel_LoginADM_Direita = new javax.swing.JPanel();
        JLBnome_projeto = new javax.swing.JLabel();
        JLBmensagemContato = new javax.swing.JLabel();
        JLBiconHospital = new javax.swing.JLabel();
        JLBemail = new javax.swing.JLabel();
        JLBfacebook = new javax.swing.JLabel();
        JLBinstagram = new javax.swing.JLabel();
        JBTalterarUser = new javax.swing.JButton();
        JLBiconADM = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CENTRAL VIDA");
        jLabel4.setAlignmentY(0.0F);

        jLabel2.setBackground(new java.awt.Color(88, 93, 96));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 98, 98));
        jLabel2.setText("Usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_LoginADM_Esquerda.setBackground(new java.awt.Color(255, 255, 255));
        Panel_LoginADM_Esquerda.setBorder(new javax.swing.border.MatteBorder(null));

        JLBsenha.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha.setText("Senha");

        JLBusuario.setBackground(new java.awt.Color(0, 0, 0));
        JLBusuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLBusuario.setText("Acesso ao Sistema");

        JTFsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFsenhaActionPerformed(evt);
            }
        });

        JTFusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuarioActionPerformed(evt);
            }
        });

        JLBusuario1.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBusuario1.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario1.setText("Usuario");

        JBTentrar.setText("Entrar");
        JBTentrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBTentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTentrarActionPerformed(evt);
            }
        });

        JLBalterarLogin.setBackground(new java.awt.Color(69, 71, 72));
        JLBalterarLogin.setForeground(new java.awt.Color(94, 94, 94));
        JLBalterarLogin.setText("deseja logar como outra funcao? clique aqui:");

        Panel_LoginADM_Direita.setBackground(new java.awt.Color(43, 104, 41));
        Panel_LoginADM_Direita.setBorder(new javax.swing.border.MatteBorder(null));

        JLBnome_projeto.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        JLBnome_projeto.setForeground(new java.awt.Color(255, 255, 255));
        JLBnome_projeto.setText("SDLEKS MED");
        JLBnome_projeto.setAlignmentY(0.0F);

        JLBmensagemContato.setBackground(new java.awt.Color(255, 255, 255));
        JLBmensagemContato.setForeground(new java.awt.Color(255, 255, 255));
        JLBmensagemContato.setText("Conecte-se conosco: entre em contato ou siga nossas redes sociais!");

        JLBiconHospital.setLabelFor(JLBiconHospital);

        javax.swing.GroupLayout Panel_LoginADM_DireitaLayout = new javax.swing.GroupLayout(Panel_LoginADM_Direita);
        Panel_LoginADM_Direita.setLayout(Panel_LoginADM_DireitaLayout);
        Panel_LoginADM_DireitaLayout.setHorizontalGroup(
            Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                .addGroup(Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JLBemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLBinstagram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBfacebook))
                    .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLBmensagemContato)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LoginADM_DireitaLayout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(JLBnome_projeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBiconHospital)
                .addGap(384, 384, 384))
        );
        Panel_LoginADM_DireitaLayout.setVerticalGroup(
            Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LoginADM_DireitaLayout.createSequentialGroup()
                .addGroup(Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                        .addGroup(Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                                .addContainerGap(168, Short.MAX_VALUE)
                                .addComponent(JLBnome_projeto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(335, 335, 335))
                            .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(JLBiconHospital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(JLBmensagemContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBfacebook))
                    .addGroup(Panel_LoginADM_DireitaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Panel_LoginADM_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLBemail)
                            .addComponent(JLBinstagram))))
                .addGap(17, 17, 17))
        );

        JBTalterarUser.setBackground(new java.awt.Color(245, 245, 245));
        JBTalterarUser.setBorder(null);
        JBTalterarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTalterarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_LoginADM_EsquerdaLayout = new javax.swing.GroupLayout(Panel_LoginADM_Esquerda);
        Panel_LoginADM_Esquerda.setLayout(Panel_LoginADM_EsquerdaLayout);
        Panel_LoginADM_EsquerdaLayout.setHorizontalGroup(
            Panel_LoginADM_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                .addGroup(Panel_LoginADM_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLBalterarLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTalterarUser))
                    .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(Panel_LoginADM_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(JBTentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JLBusuario))
                    .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(JLBiconADM)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Panel_LoginADM_Direita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        Panel_LoginADM_EsquerdaLayout.setVerticalGroup(
            Panel_LoginADM_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_LoginADM_Direita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_LoginADM_EsquerdaLayout.createSequentialGroup()
                .addComponent(JLBiconADM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JLBusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(JBTentrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_LoginADM_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBalterarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTalterarUser))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_LoginADM_Esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_LoginADM_Esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFsenhaActionPerformed

    private void JTFusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuarioActionPerformed

    private void JBTentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTentrarActionPerformed
        // Obtendo os valores dos campos
        String usuario = JTFusuario.getText();
        String senha = JTFsenha.getText();

        // Verificando se os campos não estão vazios
        if (usuario.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Usuário e senha são obrigatórios!");
            return;
        }

        // Chama o método de login da AuthManager para tentar autenticar o usuário
        String resultadoLogin = AuthManager.login(usuario, senha);

        // Verifica o resultado do login
        if (resultadoLogin.contains("Login bem-sucedido!")) {
            // Obtém a role do usuário autenticado usando o token
            String role = AuthManager.getUserRole();  // Passando o token para obter a role diretamente
            System.out.println("Role obtida: " + role);

            // Verifica a role e abre a tela correspondente
            if ("ADMIN".equals(role.trim())) {  // Removendo qualquer espaço extra antes ou depois da role
                new TELA_CENTRAL_ADM().setVisible(true);
                this.dispose();
            } else if ("RECEPCIONISTA".equals(role.trim())) {
                // new TELA_CENTRAL_RECEPCIONISTA().setVisible(true); // Tela a ser configurada posteriormente
            }

            this.dispose(); // Fecha a tela de login
        } else {
            // Caso o login falhe
            JOptionPane.showMessageDialog(this, "Falha no login! Usuário ou senha incorretos.");
        }
    }//GEN-LAST:event_JBTentrarActionPerformed

    private void JBTalterarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTalterarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTalterarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_LOGIN_ADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTalterarUser;
    private javax.swing.JButton JBTentrar;
    private javax.swing.JLabel JLBalterarLogin;
    private javax.swing.JLabel JLBemail;
    private javax.swing.JLabel JLBfacebook;
    private javax.swing.JLabel JLBiconADM;
    private javax.swing.JLabel JLBiconHospital;
    private javax.swing.JLabel JLBinstagram;
    private javax.swing.JLabel JLBmensagemContato;
    private javax.swing.JLabel JLBnome_projeto;
    private javax.swing.JLabel JLBsenha;
    private javax.swing.JLabel JLBusuario;
    private javax.swing.JLabel JLBusuario1;
    private javax.swing.JTextField JTFsenha;
    private javax.swing.JTextField JTFusuario;
    private javax.swing.JPanel Panel_LoginADM_Direita;
    private javax.swing.JPanel Panel_LoginADM_Esquerda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
