/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_consultoriomedico;

import com.mycompany.projeto_consultoriomedico.Manager.MedicoManager;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author User
 */
public class TELA_ADM_CONSULTAR_MEDICO extends javax.swing.JFrame {

    /**
     * Creates new form TELA_ADM_CONSULTAR_MEDICO
     */
    public TELA_ADM_CONSULTAR_MEDICO() {
        initComponents();
        setLocationRelativeTo(null);
        TelaUtil.padronizarTela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLBnomeClinica1 = new javax.swing.JLabel();
        JLBiconeClinica = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBTsair = new javax.swing.JButton();
        JLBversion1 = new javax.swing.JLabel();
        JLBusuario2 = new javax.swing.JLabel();
        JTFusuario = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        JLBusuario3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        JTFusuario2 = new javax.swing.JTextField();
        JLBusuario4 = new javax.swing.JLabel();
        JBTsair1 = new javax.swing.JButton();
        JLBsenha2 = new javax.swing.JLabel();
        JTFusuario3 = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        JLBversion2 = new javax.swing.JLabel();
        JBTsair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 104, 41));

        JLBnomeClinica1.setBackground(new java.awt.Color(255, 255, 255));
        JLBnomeClinica1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLBnomeClinica1.setForeground(new java.awt.Color(255, 255, 255));
        JLBnomeClinica1.setText("SDLEKS MED");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        JBTsair.setText("Voltar");
        JBTsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsairActionPerformed(evt);
            }
        });

        JLBversion1.setText("Version 0.01");

        JLBusuario2.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLBusuario2.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario2.setText("CONSULTAR MEDICO");

        JTFusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuarioActionPerformed(evt);
            }
        });

        jCheckBox1.setText("selecionar");

        JLBusuario3.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBusuario3.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario3.setText("Nome ");

        jCheckBox2.setText("selecionar");

        JTFusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuario2ActionPerformed(evt);
            }
        });

        JLBusuario4.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBusuario4.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario4.setText("CPF");

        JBTsair1.setText("Consultar");
        JBTsair1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBTsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsair1ActionPerformed(evt);
            }
        });

        JLBsenha2.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha2.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha2.setText("CRM");

        JTFusuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuario3ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("selecionar");

        JLBversion2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JLBversion2.setForeground(new java.awt.Color(88, 93, 96));
        JLBversion2.setText("OBS: SELECIONE APENAS AS INFORMACOES QUE QUEIRA UTILIZAR");

        JBTsair2.setText("Listar todos");
        JBTsair2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLBusuario2)
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JTFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JTFusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(JLBusuario3)
                            .addComponent(JLBusuario4)
                            .addComponent(JLBsenha2)
                            .addComponent(JLBversion2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JTFusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(JLBversion1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(JBTsair1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(JBTsair2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(JBTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JLBusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(JLBusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBusuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(JTFusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addComponent(JLBversion2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTsair1)
                    .addComponent(JBTsair2))
                .addGap(18, 18, 18)
                .addComponent(JBTsair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(JLBversion1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBnomeClinica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBiconeClinica)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBiconeClinica)
                    .addComponent(JLBnomeClinica1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuarioActionPerformed

    private void JTFusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuario2ActionPerformed

    private void JTFusuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuario3ActionPerformed

    private void JBTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsairActionPerformed
        this.dispose();
         TELA_ADM_VIEW_MEDICO telaAnterior = new TELA_ADM_VIEW_MEDICO();
         telaAnterior.setVisible(true);
    }//GEN-LAST:event_JBTsairActionPerformed

    private void JBTsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsair1ActionPerformed
        // Pega o CPF digitado pelo usuário
        String cpf = JTFusuario2.getText().trim();  

        // Verifica se o CPF foi preenchido
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o CPF do Medico.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Chama o método para buscar os dados do administrador pelo CPF
        String jsonResponse = MedicoManager.getMedicoByCpf(cpf);

        // Verifica se houve um erro na resposta
        if (jsonResponse.startsWith("Erro") || jsonResponse.contains("não encontrado")) {
            JOptionPane.showMessageDialog(this, "Medico não encontrado ou erro na requisição.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Converte a resposta JSON para um objeto JSONObject
            JSONObject jsonObject = new JSONObject(jsonResponse);

            // Extraímos os valores do JSON
            String nome = jsonObject.optString("nome", "Não informado");
            String cpfRecebido = jsonObject.optString("cpf", "Não informado");
            String cmr = jsonObject.optString("CMR", "Não informado");

            // Exibe os dados no JOptionPane
            String medicoInfo = "Nome: " + nome + "\n" +
                               "CPF: " + cpfRecebido + "\n" +
                               "CRM: " + cmr;

            JOptionPane.showMessageDialog(this, medicoInfo, "Dados do Medico", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao processar os dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBTsair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ADM_CONSULTAR_MEDICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ADM_CONSULTAR_MEDICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ADM_CONSULTAR_MEDICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ADM_CONSULTAR_MEDICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ADM_CONSULTAR_MEDICO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTsair;
    private javax.swing.JButton JBTsair1;
    private javax.swing.JButton JBTsair2;
    private javax.swing.JLabel JLBiconeClinica;
    private javax.swing.JLabel JLBnomeClinica1;
    private javax.swing.JLabel JLBsenha2;
    private javax.swing.JLabel JLBusuario2;
    private javax.swing.JLabel JLBusuario3;
    private javax.swing.JLabel JLBusuario4;
    private javax.swing.JLabel JLBversion1;
    private javax.swing.JLabel JLBversion2;
    private javax.swing.JTextField JTFusuario;
    private javax.swing.JTextField JTFusuario2;
    private javax.swing.JTextField JTFusuario3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
