/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_consultoriomedico.Recepcionista;

import com.mycompany.projeto_consultoriomedico.Manager.RecepcionistaManager;
import com.mycompany.projeto_consultoriomedico.TelaUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Tela_Cadastrar_Recepcionista extends javax.swing.JFrame {

    /**
     * Creates new form TELA_ADM_CADASTRAR_RECEPCIONISTA
     */
    public Tela_Cadastrar_Recepcionista() {
        initComponents();
        setLocationRelativeTo(null);
        TelaUtil.padronizarTela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JLBnomeClinica = new javax.swing.JLabel();
        JLBiconeClinica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLBsenha = new javax.swing.JLabel();
        txtCpfRec = new javax.swing.JTextField();
        txtNomeRec = new javax.swing.JTextField();
        JLBusuario1 = new javax.swing.JLabel();
        JLBusuario2 = new javax.swing.JLabel();
        JLBversion = new javax.swing.JLabel();
        JBTvoltar = new javax.swing.JButton();
        JBTsair = new javax.swing.JButton();
        JLBsenha1 = new javax.swing.JLabel();
        JLBsenha2 = new javax.swing.JLabel();
        JLBsenha3 = new javax.swing.JLabel();
        JLBsenha4 = new javax.swing.JLabel();
        JLBsenha5 = new javax.swing.JLabel();
        txtEstadoRec = new javax.swing.JTextField();
        txtCidadeRec = new javax.swing.JTextField();
        txtBairroRec = new javax.swing.JTextField();
        txtRuaRec = new javax.swing.JTextField();
        txtNumeroRec = new javax.swing.JTextField();
        JLBsenha6 = new javax.swing.JLabel();
        txtTelefoneRec = new javax.swing.JTextField();
        JLBsenha7 = new javax.swing.JLabel();
        txtLoginRec = new javax.swing.JTextField();
        JLBsenha8 = new javax.swing.JLabel();
        txtSenhaRec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(43, 104, 41));

        JLBnomeClinica.setBackground(new java.awt.Color(255, 255, 255));
        JLBnomeClinica.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        JLBnomeClinica.setForeground(new java.awt.Color(255, 255, 255));
        JLBnomeClinica.setText("SDLEKS MED");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(JLBnomeClinica)
                .addGap(18, 18, 18)
                .addComponent(JLBiconeClinica)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLBnomeClinica)
                    .addComponent(JLBiconeClinica))
                .addContainerGap(630, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        JLBsenha.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha.setText("CPF");

        txtCpfRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfRecActionPerformed(evt);
            }
        });

        txtNomeRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRecActionPerformed(evt);
            }
        });

        JLBusuario1.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBusuario1.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario1.setText("Nome Completo");

        JLBusuario2.setBackground(new java.awt.Color(88, 93, 96));
        JLBusuario2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLBusuario2.setForeground(new java.awt.Color(101, 98, 98));
        JLBusuario2.setText("CADASTRAR RECEPCIONISTA");

        JLBversion.setText("Version 0.01");

        JBTvoltar.setText("Cadastrar");
        JBTvoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBTvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltarActionPerformed(evt);
            }
        });

        JBTsair.setText("Voltar");
        JBTsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsairActionPerformed(evt);
            }
        });

        JLBsenha1.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha1.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha1.setText("Bairro");

        JLBsenha2.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha2.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha2.setText("Estado");

        JLBsenha3.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha3.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha3.setText("Cidade");

        JLBsenha4.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha4.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha4.setText("Login");

        JLBsenha5.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha5.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha5.setText("Rua");

        txtEstadoRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoRecActionPerformed(evt);
            }
        });

        txtCidadeRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeRecActionPerformed(evt);
            }
        });

        txtBairroRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroRecActionPerformed(evt);
            }
        });

        txtRuaRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaRecActionPerformed(evt);
            }
        });

        txtNumeroRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroRecActionPerformed(evt);
            }
        });

        JLBsenha6.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha6.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha6.setText("Número");

        txtTelefoneRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneRecActionPerformed(evt);
            }
        });

        JLBsenha7.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha7.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha7.setText("Telefone");

        txtLoginRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginRecActionPerformed(evt);
            }
        });

        JLBsenha8.setBackground(new java.awt.Color(88, 93, 96));
        JLBsenha8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBsenha8.setForeground(new java.awt.Color(101, 98, 98));
        JLBsenha8.setText("Senha");

        txtSenhaRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBusuario2)
                            .addComponent(JLBsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBusuario1)
                            .addComponent(JLBsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBsenha8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSenhaRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefoneRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRuaRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBairroRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCidadeRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(txtCpfRec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEstadoRec, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(JLBversion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(JBTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(JBTvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JLBusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBsenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtCidadeRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBsenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBairroRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBsenha5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRuaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(JLBsenha6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JLBsenha7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefoneRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBsenha4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLoginRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBsenha8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenhaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTvoltar)
                .addGap(12, 12, 12)
                .addComponent(JBTsair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBversion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfRecActionPerformed
        txtCpfRec.getText();
    }//GEN-LAST:event_txtCpfRecActionPerformed

    private void txtNomeRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRecActionPerformed
        txtNomeRec.getText();
    }//GEN-LAST:event_txtNomeRecActionPerformed

    private void JBTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsairActionPerformed
        this.dispose();
         TTTT telaAnterior = new TTTT();
         telaAnterior.setVisible(true);
    }//GEN-LAST:event_JBTsairActionPerformed

    private void JBTvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltarActionPerformed
       String nome = txtNomeRec.getText();
        String cpf = txtCpfRec.getText();
        String estado =  txtEstadoRec.getText();
        String cidade =  txtCidadeRec.getText();
        String bairro=  txtBairroRec.getText();
        String rua =  txtRuaRec.getText();
        int numero = Integer.parseInt(txtNumeroRec.getText());
        String telefone =  txtTelefoneRec.getText();
        String login =  txtLoginRec.getText();
        String  password =  txtSenhaRec.getText();

        String response = RecepcionistaManager.createRecepcionista(nome, cpf, estado, cidade, bairro, rua, numero , telefone, login, password);
        JOptionPane.showMessageDialog(null, response);
    }//GEN-LAST:event_JBTvoltarActionPerformed

    private void txtEstadoRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoRecActionPerformed
        txtEstadoRec.getText();
    }//GEN-LAST:event_txtEstadoRecActionPerformed

    private void txtCidadeRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeRecActionPerformed
        txtCidadeRec.getText();
    }//GEN-LAST:event_txtCidadeRecActionPerformed

    private void txtBairroRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroRecActionPerformed
        txtBairroRec.getText();
    }//GEN-LAST:event_txtBairroRecActionPerformed

    private void txtRuaRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaRecActionPerformed
        txtRuaRec.getText();
    }//GEN-LAST:event_txtRuaRecActionPerformed

    private void txtNumeroRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroRecActionPerformed
        txtNumeroRec.getText();
    }//GEN-LAST:event_txtNumeroRecActionPerformed

    private void txtTelefoneRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneRecActionPerformed
        txtTelefoneRec.getText();
    }//GEN-LAST:event_txtTelefoneRecActionPerformed

    private void txtLoginRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginRecActionPerformed
        txtLoginRec.getText();
    }//GEN-LAST:event_txtLoginRecActionPerformed

    private void txtSenhaRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaRecActionPerformed
        txtSenhaRec.getText();
    }//GEN-LAST:event_txtSenhaRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastrar_Recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTsair;
    private javax.swing.JButton JBTvoltar;
    private javax.swing.JLabel JLBiconeClinica;
    private javax.swing.JLabel JLBnomeClinica;
    private javax.swing.JLabel JLBsenha;
    private javax.swing.JLabel JLBsenha1;
    private javax.swing.JLabel JLBsenha2;
    private javax.swing.JLabel JLBsenha3;
    private javax.swing.JLabel JLBsenha4;
    private javax.swing.JLabel JLBsenha5;
    private javax.swing.JLabel JLBsenha6;
    private javax.swing.JLabel JLBsenha7;
    private javax.swing.JLabel JLBsenha8;
    private javax.swing.JLabel JLBusuario1;
    private javax.swing.JLabel JLBusuario2;
    private javax.swing.JLabel JLBversion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBairroRec;
    private javax.swing.JTextField txtCidadeRec;
    private javax.swing.JTextField txtCpfRec;
    private javax.swing.JTextField txtEstadoRec;
    private javax.swing.JTextField txtLoginRec;
    private javax.swing.JTextField txtNomeRec;
    private javax.swing.JTextField txtNumeroRec;
    private javax.swing.JTextField txtRuaRec;
    private javax.swing.JTextField txtSenhaRec;
    private javax.swing.JTextField txtTelefoneRec;
    // End of variables declaration//GEN-END:variables
}
